---
- name: hardware
  ansible.builtin.include_tasks:
    file: hardware.yml

- name: build
  ansible.builtin.include_tasks:
    file: build.yml
  when: build_image


# Backup old image
- name: backup
  ansible.builtin.include_tasks:
    file: backup.yml
